output_dir: /z/home/frma/projects/DNA-LM/downstream_tasks/enhancer_classification/below50k_validated/split_chromosome/convnet_supervised/split${data.partition_split}/
model:
  _target_: models.downstream.ConvNetModel
  output_size: ${datadims.${data.label_type}}
  n_layers: 30
  hidden_size: 256
  output_downsample_window: null
data:
  _target_: utils.data_downstream.split_data
  partition_split : 10
  dir: /z/home/frma/projects/DNA-LM/data/gene_enhancer_pair/
  data: ${data.dir}/torch_files/
  indices: ${data.dir}/partitions/below50k/only_validated/split_on_chromosome/split${data.partition_split}.csv
  same_set: false
  split: null
  num_workers: 32
  sample_strand: false
  sample_by_length: false
  batch_size: 4
  seed: 42
  ignore_index: -100
  label_type: enhancer
  feature_type: dna
  embedding:
    embedding_type: categorical
  keys:
  - dna
  - label
  - validated
params:
  epochs: 100
  lr: 0.003
  weight_decay: 0.01
  load_checkpoint: false
  gradient_accumulation_steps: 2
  mode: train
  criterion: cross_entropy
  class_weights:
  - 1
  - 82.86
wandb:
  mode: offline
  entity: fmarin
  project: dna-lm-enhancer
  name: DCNN-supervised
datadims:
  simple_DA: 5
  simple_direction_DA: 9
  codon_direction_DA: 25
  onehot: 5
  gpn: 512
  nt_transformer_2B5_1000G: 2560
  nt_transformer_2B5_multi_species: 2560
  nt_transformer_500M_1000G: 1280
  nt_transformer_500M_human_ref: 1280
  convnet: 256
  cage_human: 638
  enhancer: 2
