defaults:
  - datadims : [label_dims,embedding_dims]
  - _self_
hydra : 
  searchpath:
    #- pkg://conf
    - file://conf 
task : enhancer_annotation 
embedder : resnetlm
output_dir: ./downstream_tasks/${task}/${embedder}/split_${data.cross_validation}
model:
  _target_: bend.models.downstream.CNN
  input_size: ${datadims.${embedder}}
  output_size: ${datadims.${task}}
  hidden_size: 2
  kernel_size: 3
  upsample_factor: null
  output_downsample_window: null
optimizer : 
  _target_ : torch.optim.AdamW 
  lr : 0.001
  weight_decay: 0.01
data:
  _target_: bend.utils.data_downstream.get_data
  cross_validation : false
  batch_size : 8
  num_workers : 0
  padding_value : -100
  shuffle : 500
  data_dir : ./data/${task}/${embedder}/
  cross_validation : 1 # which split to run in the cross validation
params:
  epochs: 100
  load_checkpoint: false
  mode: train
  gradient_accumulation_steps: 1
  criterion: cross_entropy
  class_weights:
  - 1
  - 82.86
  metric : mcc
  activation : none
wandb:
  mode : disabled 
