defaults:
  - datadims : [label_dims,embedding_dims]
  - _self_
hydra : 
  searchpath:
    - file://conf 
task : gene_finding 
embedder : gena-lm-bert-large-t2
output_dir: ./downstream_tasks/${task}/${embedder}/
model:
  _target_: bend.models.downstream.CNN
  input_size: ${datadims.${embedder}}
  output_size: ${datadims.${task}}
  hidden_size: 64
  kernel_size: 3
optimizer : 
  _target_ : torch.optim.AdamW 
  lr : 0.003
  weight_decay: 0.01
data:
  _target_: bend.utils.data_downstream.get_data
  dir : /z/datasets/ds_er_etl/frma/data
  data_dir : ${data.dir}/${task}/${embedder}/
  cross_validation : false
  batch_size : 64
  num_workers : 0
  padding_value : -100
  shuffle : 5000
  train_data : [train.tfrecord]
  valid_data : [valid.tfrecord]
  test_data :  [test.tfrecord]
params:
  epochs: 100
  load_checkpoint: false
  mode: train
  gradient_accumulation_steps: 1
  criterion: cross_entropy
  class_weights: null
  metric : mcc
  activation : none
wandb:
  mode : disabled 