defaults:
  - datadims : [label_dims,embedding_dims]
  - _self_
hydra : 
  searchpath:
    - file://conf 
task : chromatin_accessibility 
embedder : hyenadna-tiny-1k
output_dir: ./downstream_tasks/${task}/${embedder}/
model:
  _target_: bend.models.downstream.CNN
  input_size: ${datadims.${embedder}}
  output_size: ${datadims.${task}}
  hidden_size: 64
  kernel_size: 3
  output_downsample_window: 512
optimizer : 
  _target_ : torch.optim.AdamW 
  lr : 0.003
  weight_decay: 0.01
data:
  _target_: bend.utils.data_downstream.get_data
  data_dir : ./data/${task}/${embedder}/
  cross_validation : false
  batch_size : 512
  num_workers : 0
  padding_value : -100
  shuffle : 5000
  train_data : [train.tfrecord]
  valid_data : [valid.tfrecord]
  test_data :  [test.tfrecord]
params:
  epochs: 100
  load_checkpoint: false
  mode: train
  gradient_accumulation_steps: 1
  criterion: bce
  class_weights: null
  metric : auroc
  activation : none
wandb:
  mode : disabled 


