hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - data.partition_split=1
  job:
    name: train_downstream
    chdir: null
    override_dirname: data.partition_split=1
    id: ???
    num: ???
    config_name: awdlstm.yaml
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.1
    version_base: '1.3'
    cwd: /nfs/home/frma/projects/BEND/scripts
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /nfs/home/frma/projects/BEND/scripts/conf/supervised_tasks/enhancer_annotation
      schema: file
      provider: main
    - path: /nfs/home/frma/projects/BEND/bend/conf
      schema: file
      provider: command-line
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
output_dir: /z/home/frma/projects/DNA-LM/test/
model:
  _target_: models.downstream.CNN
  input_size: ${datadims.${data.feature_type}}
  output_size: ${datadims.${data.label_type}}
  hidden_size: 2
  kernel_size: 3
  upsample_factor: null
  output_downsample_window: null
data:
  _target_: utils.data_downstream.split_data
  partition_split: 1
  dir: /z/home/frma/projects/DNA-LM/data/gene_enhancer_pair/
  data: ${data.dir}/torch_files/
  indices: ${data.dir}/partitions/below50k/only_validated/split_on_chromosome/split${data.partition_split}.csv
  same_set: false
  split: null
  num_workers: 32
  sample_strand: false
  sample_by_length: false
  batch_size: 8
  seed: 42
  ignore_index: -100
  label_type: enhancer
  feature_type: awdlstm
  embedding: null
  superset_factor: 1
  keys:
  - features_awdlstm
  - label
params:
  epochs: 100
  lr: 0.001
  weight_decay: 0.01
  load_checkpoint: false
  gradient_accumulation_steps: 1
  mode: train
  criterion: cross_entropy
  metric: mcc
  class_weights:
  - 1
  - 82.86
wandb:
  mode: disabled
  entity: null
  project: null
  name: null
datadims:
  simple_DA: 5
  simple_direction_DA: 9
  codon_direction_DA: 25
  onehot: 5
  gpn: 512
  nt_transformer_2B5_1000G: 2560
  nt_transformer_2B5_multi_species: 2560
  nt_transformer_500M_1000G: 1280
  nt_transformer_500M_human_ref: 1280
  convnet: 256
  cage_human: 638
  enhancer: 2
  dnabert: 768
  awdlstm: 64
